- name: Mount a stake Pool ** 30 near token is needed to stake a pool **
  shell:  |
    near call factory.shardnet.near create_staking_pool '{"staking_pool_id": "factory.shardnet.near", "owner_id": "{{ account_id }}", "stake_public_key": "{{ public_key }}", "reward_fee_fraction": {"numerator": 5, "denominator": 100}, "code_hash":"DD428g9eqLL8fWUxv8QSpVFzyHi1Qd16P8ephYCTmMSZ"}' --accountId="{{ account_id }}" --amount=30 --gas=300000000000000
  register: output
- debug: msg="{{ output.stdout }}"
  register: output
- debug: msg="{{ output.stdout }}"