- name: Verify CPU minimum requirements
  shell:  | 
    lscpu | grep -P '(?=.*avx )(?=.*sse4.2 )(?=.*cx16 )(?=.*popcnt )' > /dev/null && echo "Supported" || echo "Not supported"
  register: output
- debug: msg="{{ output.stdout }}"