---

- name: Clean old ping.sh path
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_env.HOME }}/logs"

- name: Make the logs directory folder
  shell: mkdir {{ ansible_env.HOME }}/logs

- name: Copy ping.sh to log directory
  tags: near uptime
  template: src=script/ping.sh.j2 dest=/{{ ansible_env.HOME }}/logs/ping.sh
  become: yes

- name:  Create a cronjob for near uptime
  ansible.builtin.cron:
    name: "test"
    state: present
    minute: "*"
    hour:  "2"
    day: "*"
    month: "*"
    weekday: "*"
    job: '{{ ansible_env.HOME }}/logs/ping.sh'